-- Выполните этот файл целиком в Supabase Dashboard → SQL Editor.

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(trim(name)) > 0)
);

create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 1 and 6),
  lesson_number smallint not null check (lesson_number > 0),
  subject_name text not null check (length(trim(subject_name)) > 0),
  time_start time not null,
  time_end time not null,
  check (time_end > time_start),
  unique (group_id, day_of_week, lesson_number)
);

create table if not exists public.telegram_users (
  telegram_user_id bigint primary key,
  chat_id bigint not null,
  group_id bigint not null references public.groups(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists schedule_group_day_idx
  on public.schedule (group_id, day_of_week, lesson_number);

create index if not exists telegram_users_group_idx
  on public.telegram_users (group_id);

alter table public.groups enable row level security;
alter table public.schedule enable row level security;
alter table public.telegram_users enable row level security;

drop policy if exists "groups_are_publicly_readable" on public.groups;
create policy "groups_are_publicly_readable"
  on public.groups
  for select
  to anon, authenticated
  using (true);

drop policy if exists "schedule_is_publicly_readable" on public.schedule;
create policy "schedule_is_publicly_readable"
  on public.schedule
  for select
  to anon, authenticated
  using (true);

grant usage on schema public to anon, authenticated;
grant select on public.groups, public.schedule to anon, authenticated;

insert into public.groups (name)
values
  ('ПО-41'),
  ('ИС-22')
on conflict (name) do nothing;

-- ПО-41: понедельник, среда и четверг.
insert into public.schedule (
  group_id,
  day_of_week,
  lesson_number,
  subject_name,
  time_start,
  time_end
)
select
  g.id,
  lesson.day_of_week,
  lesson.lesson_number,
  lesson.subject_name,
  lesson.time_start,
  lesson.time_end
from public.groups as g
cross join (
  values
    (1::smallint, 1::smallint, 'Компьютерные сети'::text, '08:30'::time, '09:50'::time),
    (1::smallint, 2::smallint, 'Web-разработка'::text, '09:55'::time, '11:15'::time),
    (1::smallint, 3::smallint, 'Базы данных'::text, '11:25'::time, '12:45'::time),
    (3::smallint, 1::smallint, 'Операционные системы'::text, '08:30'::time, '09:50'::time),
    (3::smallint, 2::smallint, 'Компьютерные сети'::text, '09:55'::time, '11:15'::time),
    (3::smallint, 3::smallint, 'Английский язык'::text, '11:25'::time, '12:45'::time),
    (4::smallint, 1::smallint, 'Web-разработка'::text, '08:30'::time, '09:50'::time),
    (4::smallint, 2::smallint, 'Базы данных'::text, '09:55'::time, '11:15'::time),
    (4::smallint, 3::smallint, 'Информационная безопасность'::text, '11:25'::time, '12:45'::time)
) as lesson(day_of_week, lesson_number, subject_name, time_start, time_end)
where g.name = 'ПО-41'
on conflict (group_id, day_of_week, lesson_number) do update
set
  subject_name = excluded.subject_name,
  time_start = excluded.time_start,
  time_end = excluded.time_end;

-- ИС-22: вторник, четверг и суббота.
insert into public.schedule (
  group_id,
  day_of_week,
  lesson_number,
  subject_name,
  time_start,
  time_end
)
select
  g.id,
  lesson.day_of_week,
  lesson.lesson_number,
  lesson.subject_name,
  lesson.time_start,
  lesson.time_end
from public.groups as g
cross join (
  values
    (2::smallint, 1::smallint, 'Математика'::text, '08:30'::time, '09:50'::time),
    (2::smallint, 2::smallint, 'Основы программирования'::text, '09:55'::time, '11:15'::time),
    (2::smallint, 3::smallint, 'Физическая культура'::text, '11:25'::time, '12:45'::time),
    (4::smallint, 1::smallint, 'Базы данных'::text, '08:30'::time, '09:50'::time),
    (4::smallint, 2::smallint, 'Проектирование систем'::text, '09:55'::time, '11:15'::time),
    (4::smallint, 3::smallint, 'Web-технологии'::text, '11:25'::time, '12:45'::time),
    (6::smallint, 1::smallint, 'Основы алгоритмизации'::text, '08:30'::time, '09:50'::time),
    (6::smallint, 2::smallint, 'Архитектура компьютеров'::text, '09:55'::time, '11:15'::time)
) as lesson(day_of_week, lesson_number, subject_name, time_start, time_end)
where g.name = 'ИС-22'
on conflict (group_id, day_of_week, lesson_number) do update
set
  subject_name = excluded.subject_name,
  time_start = excluded.time_start,
  time_end = excluded.time_end;
