const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const sqlPath = path.resolve(__dirname, '..', 'database.sql');

test('database defines the requested tables and relationship', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /create table if not exists public\.groups/i);
  assert.match(sql, /create table if not exists public\.schedule/i);
  assert.match(sql, /id\s+bigint\s+generated by default as identity\s+primary key/i);
  assert.match(sql, /group_id\s+bigint\s+not null\s+references public\.groups\s*\(id\)/i);
  assert.match(sql, /on delete cascade/i);
  assert.match(sql, /day_of_week\s+smallint\s+not null\s+check\s*\(day_of_week between 1 and 6\)/i);
  assert.match(sql, /lesson_number\s+smallint\s+not null\s+check\s*\(lesson_number > 0\)/i);
  assert.match(sql, /check\s*\(time_end > time_start\)/i);
  assert.match(sql, /unique\s*\(group_id, day_of_week, lesson_number\)/i);
  assert.match(sql, /create index if not exists schedule_group_day_idx/i);
});

test('database enables public read-only RLS', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /alter table public\.groups enable row level security/i);
  assert.match(sql, /alter table public\.schedule enable row level security/i);
  assert.match(sql, /create policy "groups_are_publicly_readable"[\s\S]*for select[\s\S]*to anon, authenticated[\s\S]*using \(true\)/i);
  assert.match(sql, /create policy "schedule_is_publicly_readable"[\s\S]*for select[\s\S]*to anon, authenticated[\s\S]*using \(true\)/i);
  assert.doesNotMatch(sql, /create policy[\s\S]{0,120}for\s+(insert|update|delete|all)/i);
});

test('database seeds both groups for every teaching weekday', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /ПО-41/);
  assert.match(sql, /ИС-22/);
  assert.match(sql, /Компьютерные сети/);
  assert.match(sql, /Web-разработка/);
  assert.match(sql, /Базы данных/);
  assert.match(sql, /on conflict \(name\) do nothing/i);
  assert.match(sql, /on conflict \(group_id, day_of_week, lesson_number\) do update/i);

  const [po41Block, is22Block] = sql.split('-- ИС-22:');
  for (const [group, block] of [['ПО-41', po41Block], ['ИС-22', is22Block]]) {
    const weekdays = [...block.matchAll(/\(\s*([1-6])::smallint,\s*\d+::smallint/g)].map(
      (match) => match[1],
    );
    for (let day = 1; day <= 6; day += 1) {
      assert.ok(weekdays.includes(String(day)), `expected ${group} schedule on weekday ${day}`);
    }
  }
});

test('database stores Telegram preferences behind RLS without public policies', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /create table if not exists public\.telegram_users/i);
  assert.match(sql, /telegram_user_id\s+bigint\s+primary key/i);
  assert.match(sql, /chat_id\s+bigint\s+not null/i);
  assert.match(sql, /group_id\s+bigint\s+not null\s+references public\.groups\s*\(id\)\s+on delete cascade/i);
  assert.match(sql, /created_at\s+timestamptz\s+not null\s+default now\(\)/i);
  assert.match(sql, /updated_at\s+timestamptz\s+not null\s+default now\(\)/i);
  assert.match(sql, /create index if not exists telegram_users_group_idx/i);
  assert.match(sql, /alter table public\.telegram_users enable row level security/i);
  assert.doesNotMatch(sql, /create policy[^;]+on public\.telegram_users/is);
  assert.doesNotMatch(sql, /grant[^;]+telegram_users/is);
});

test('database seeds the recurring PO-42 schedule with lesson details', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /teacher_name\s+text/i);
  assert.match(sql, /room\s+text/i);
  assert.match(sql, /alter table public\.schedule\s+add column if not exists teacher_name text/i);
  assert.match(sql, /alter table public\.schedule\s+add column if not exists room text/i);
  assert.match(sql, /'ПО-42'/);
  assert.match(sql, /Селиверстов К\.О\./);
  assert.match(sql, /Тукубаев А\.С\./);
  assert.match(sql, /Злочевская С\.В\./);
  assert.match(sql, /Коломиец В\.С\./);
  assert.match(sql, /'10:40'::time, '12:00'::time/);
  assert.match(sql, /'10:10'::time, '11:40'::time/);
  assert.match(sql, /where g\.name = 'ПО-42'/i);
  assert.match(sql, /teacher_name = excluded\.teacher_name/i);
  assert.match(sql, /room = excluded\.room/i);

  const po42Block = sql.split('-- ПО-42:')[1].split('-- ИС-22:')[0];
  const rows = [...po42Block.matchAll(/\(\s*([1-6])::smallint,\s*([1-5])::smallint,/g)];
  assert.equal(rows.length, 20);
  assert.deepEqual(new Set(rows.map((match) => match[1])), new Set(['1', '2', '3', '4', '5']));
});
