const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const sqlPath = path.resolve(__dirname, '..', 'database.sql');

test('database defines the requested tables and relationship', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /create table if not exists public\.groups/i);
  assert.match(sql, /create table if not exists public\.schedule/i);
  assert.match(sql, /id\s+bigint\s+generated by default as identity\s+primary key/i);
  assert.match(sql, /group_id\s+bigint\s+not null\s+references public\.groups\s*\(id\)/i);
  assert.match(sql, /on delete cascade/i);
  assert.match(sql, /day_of_week\s+smallint\s+not null\s+check\s*\(day_of_week between 1 and 6\)/i);
  assert.match(sql, /lesson_number\s+smallint\s+not null\s+check\s*\(lesson_number > 0\)/i);
  assert.match(sql, /check\s*\(time_end > time_start\)/i);
  assert.match(sql, /unique\s*\(group_id, day_of_week, lesson_number\)/i);
  assert.match(sql, /create index if not exists schedule_group_day_idx/i);
});

test('database enables public read-only RLS', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /alter table public\.groups enable row level security/i);
  assert.match(sql, /alter table public\.schedule enable row level security/i);
  assert.match(sql, /create policy "groups_are_publicly_readable"[\s\S]*for select[\s\S]*to anon, authenticated[\s\S]*using \(true\)/i);
  assert.match(sql, /create policy "schedule_is_publicly_readable"[\s\S]*for select[\s\S]*to anon, authenticated[\s\S]*using \(true\)/i);
  assert.doesNotMatch(sql, /create policy[\s\S]{0,120}for\s+(insert|update|delete|all)/i);
});

test('database seeds two groups across multiple weekdays', () => {
  const sql = fs.readFileSync(sqlPath, 'utf8');

  assert.match(sql, /ПО-41/);
  assert.match(sql, /ИС-22/);
  assert.match(sql, /Компьютерные сети/);
  assert.match(sql, /Web-разработка/);
  assert.match(sql, /Базы данных/);
  assert.match(sql, /on conflict \(name\) do nothing/i);
  assert.match(sql, /on conflict \(group_id, day_of_week, lesson_number\) do update/i);

  const weekdays = [...sql.matchAll(/\(\s*([1-6])::smallint,\s*\d+::smallint/g)].map(
    (match) => match[1],
  );
  assert.ok(new Set(weekdays).size >= 3);
});
